### PR TITLE
Adds addtional info to loki and tempo-mixin configmaps

### PR DESCRIPTION
**Pull request by SonnyAD**
This PR adds `addtionalAnnotations` and `annotationsLabels` to the config maps for the dashboard.

### CODE REVIEW

**Comment by nlamirault** [comment]
could you please add also default entries into the values.yaml file ?

**Comment by nlamirault** [comment]
also could you try to add into helper instead of manifest file
Like that: https://github.com/portefaix/portefaix-hub/blob/master/charts/bbox-exporter/templates/_helpers.tpl#L67

**Comment by SonnyAD** [comment]
> also could you try to add into helper instead of manifest file Like that: https://github.com/portefaix/portefaix-hub/blob/master/charts/bbox-exporter/templates/_helpers.tpl#L67

Done. I also added them in `loki-mixin` FYI, because I need it too on my end. 

Regarding the default values, I can see they already have `{}` set in the values.yaml. Feel free to let me know if you would like me to add anything else.

**Comment by nlamirault** [comment]
could you please make a `minor` change to the charts versions. Thanks.

**Comment by SonnyAD** [comment]
Done, please have a look 👍

**Comment by nlamirault** [comment]
could you please add default values for additionalLabels ?

```yaml
# -- Additional labels to add to all resources
additionalLabels: {}

# -- Additional annotations to add to all resources
additionalAnnotations: {}
```

**Comment by nlamirault** [comment]
Thanks

**Pull request merged**
